---
# tasks file for jsnshrmn.galen

- include: yum.yml
  become: true

- include: nvm.yml
  become: true
  become_user: "{{ galen_user }}"
  environment:
    NVM_DIR: "/home/{{ galen_user }}/.nvm"

- include: Xvfb.yml
  become: true
